 '/' GET *.index
 /register POST *.register
 /login POST *.login
 /items/ POST *.create
 /items/:id GET *.show
 /items/:id PUT *.edit
 /items/:id DELETE *.DELETE
 /items/:id/contact POST *.nodemailer
 /creators/ POST *.create
 /creators/:id GET *.show
 /creators/:id PUT *.edit
