const CategoriesData = [
  { value: 'wood', label: 'Wood' },
  { value: 'metal', label: 'Metal' },
  { value: 'creative', label: 'Creative' },
  { value: 'stairs', label: 'Stairs' },
  { value: 'chair', label: 'Chair' },
  { value: 'wicker', label: 'Wicker' },
  { value: 'lights', label: 'Lights' },
  { value: 'hanging', label: 'Hanging' },
  { value: 'kitchen', label: 'Kitchen' },
  { value: 'bedroom', label: 'Bedroom' },
  { value: 'rail', label: 'Rail' },
  { value: 'mounted', label: 'Mounted' },
  { value: 'bathroom', label: 'Bathroom' },
  { value: 'drawers', label: 'Drawers' },
  { value: 'storage', label: 'Storage' },
  { value: 'homemade', label: 'Homemade' },
  { value: 'stand', label: 'Stand' },
  { value: 'living', label: 'Living' },
  { value: 'steel', label: 'Steel' },
  { value: 'coats', label: 'Coats' },
  { value: 'art', label: 'Art' },
  { value: 'lamp', label: 'Lamp' },
  { value: 'relax', label: 'Relax' },
  { value: 'outdoors', label: 'Outdoors' },
  { value: 'flowers', label: 'Flowers' },
  { value: 'clock', label: 'Clock' },
  { value: 'bed', label: 'Bed' },
  { value: 'boxes', label: 'Boxes' },
  { value: 'chic', label: 'Chic' },
  { value: 'indoor', label: 'Indoor' },
  { value: 'lighting', label: 'Lighting' },
  { value: 'study', label: 'Study' },
  { value: 'sofa', label: 'Sofa' },
  { value: 'wooden', label: 'Wooden' },
  { value: 'mirror', label: 'Mirror' },
  { value: 'shelves', label: 'Shelves' },
  { value: 'outdoors', label: 'Outdoors' }
]

export default CategoriesData
